# Generated by Django 5.1.15 on 2026-07-29 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
