# Generated by Django 5.1.15 on 2026-07-31 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_donation_is_anonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='order_tracking_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='donation',
            name='payment_status',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
